### ISSUE TITLE
Rooms fail when containing "/"

### ISSUE THREAD

**Issue by Sonderwoods** [ladybug-tools/honeybee-grasshopper-radiance#181]
https://github.com/ladybug-tools/honeybee-grasshopper-radiance/blob/a04999c20eb67133931f2250f18d6d3aa8d4d0e4/honeybee_grasshopper_radiance/src/HB%20Sensor%20Grid.py#L66

Why not replace("/","_")  in input room name? My daylight simulations are failing if my room names contain a forward slash.

Otherwise both in daylight factor simulation and annual daylight simulation you'll get this error:

```
Runtime error (PythonException): The recipe failed to run with the following summary:

Scheduled 9 tasks of which:
* 6 ran successfully:
    - 1 CreateOctree(...)
    - 1 CreateRadFolder(...)
    - 1 DaylightFactorRayTracing(...)
    - 1 DaylightFactorRayTracingLoop(...)
    - 1 GenerateSky(...)
    ...
* 1 failed:
    - 1 RestructureResults(...)
* 2 were left pending, among these:
    * 2 had failed dependencies:
        - 1 LetDaylightFactorFly(...)
        - 1 _Main_c4ed2ed7Orchestrator(...)

This progress looks :( because there were failed tasks

Use the report_out attribute of recipe settings to see a full report.

Traceback:
  line 82, in script
```

**Comment by chriswmackey** [comment]
Hey @Sonderwoods ,

Sorry for the late response. How you are you able to create a Room with a `/` in the Radiance Simulation Name (aka. the identifier?) You'll see that the `clean_rad_string` method that you reference there removed all special characters, including `/`:

https://github.com/ladybug-tools/honeybee-core/blob/master/honeybee/typing.py#L187-L200

![image](https://user-images.githubusercontent.com/5567574/153922055-46d3e1be-3c7b-4395-a538-35739666247f.png)

@mostaphaRoudsari , I guess you must still be using the Grid display_name somewhere in these recipes instead of the identifier and the issue results from us deriving the display_name of the grid from the display_name of the Room?

**Comment by chriswmackey** [comment]
Actually, I just checked and I was unable to recreate the issue:

![image](https://user-images.githubusercontent.com/5567574/153923066-c3cec5e7-3c2a-4530-99b4-e71f3280e5b8.png)
https://drive.google.com/file/d/14zYTt4Qhep7fr2DxO5mizECjajcrDHNF/view?usp=sharing
If you have a sample that can re-create the error with the latest development version of the plugin,. @Sonderwoods , please upload it and reopen.

I am going to close this issue for now since it seems to be fixed in the latest version of the plugin.

**Comment by mostaphaRoudsari** [comment]
A sensor grid can be part of a group. For instance, `daylight/living_room` vs `radiation/living_room`. This allows us to use the same HBJSON file for several different daylight studies without the need to create several of them for each study. That's why we don't replace '/' with '_'
