### ISSUE TITLE
The reason behind adding an id to object names including sensors and modifiers

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/honeybee-grasshopper-radiance#19]
Hi @chriswmackey,

I see that you are adding an id to the name even if a specific name has already been provided. Can you tell me more why is this required?

![image](https://user-images.githubusercontent.com/2915573/86424777-6b151b00-bcb1-11ea-8915-ee8872928fea.png)

I personally expect to get the exact same name when it has been provided explicitly by the user. This will break the workflows that will take a grid name as an input unless we update them every single time since it will changing randomly. That's not a desired behavior IMO but I might be missing something here.

**Comment by mostaphaRoudsari** [comment]
I just realized that the same is happening in other components including the modifier component. I'm not really a fan but I'm sure you had a reason to do this. Hopefully there is a way to remove them. It is critical to be able to keep track of the modifier or face names that has been provided explicitly.

**Comment by chriswmackey** [comment]
This was all apart of the name-to-identifier change, which all of the plugins have now undergone including Rhino, Revit, and Grasshopper.  All of the plugins use the `identifier` for any case that a unique id is needed and the responsibility of a human-readable name is now handled by the `display_name` that all of these objects have. Along these lines, @MingboPeng ,@ksobon and I have all implemented some functions that generate unique IDs for the user whenever this unique identifier is needed.  I know Mingbo and Konrad took this to even more of an extreme than I did, using almost excursively UUIDs for this purpose (you see that I try to build a hybrid of cleaned user input and a few unique characters such that advanced users delving into IDFs and rad files don't feel like they are in the dark).  But I presently lost the battle to convince Mingbo and Konrad that part of a user-specified name should be incorporated into identifiers so you might need to convince them to at least budge before you convince me that we should wholly trust the user to always know what their unique identifiers are and not make naming conflicts.

As it stands now, I think Mingbo, Konrad, Michal, and I are all in agreement that using a user-specified name as an identifier is all well and good when you are building small test boxes but it doesn't scale. It's very difficult to avoid name conflicts when building large models or you want to combine the objects of one model with another model. So it's best just to ensure that the identifiers are always unique whenever they originate from a user and separate out the desire for something human-readable into it's own `display_name`.

It may also be worth highlighting that the `display_name` of the sensor grid is equal to the exact input that you specified for this component. So if it's the aesthetics from the interface that bug you, we can just change the `__repr__` to show the display name instead of the identifier.  We can also try to match things with the display name if you are worried about data matching down the road, though I have found so far that it makes the most sense to match based on ID. It's also worth noting that, as a developer using the Python libraries, you can always set the identifier to whatever you want. We just want to stop the thousands of non-developers who aren't as advanced as us from creating what will surely be an enormous support headache for us with tons of naming conflicts across the several models they have for one project, for example.

**Comment by chriswmackey** [comment]
Maybe it's also worth highlighting that, when Mingbo, Konrad, and Michal were first trying to convince me that this was the way to go, I had the exact same reaction that you did. But, now that this has been in place for 3 months and I have been using this system along with SOM, Michael Donn, etc., I have to say that the convenience of having a unique ID for everything has far outweighed any detriment of not being able to specify exactly what the ID is for an object from the Grasshopper component. If I or SOM has ever need to save an object with it's ID and load it in another Grasshopper file that uses the ID to match it to something else, we just serialize it to JSON and load it up in the other file. We let the Grasshopper script be just that - a script and not a static model or an object. It's the job of a JSON if you want to save something static. And, any case where I have REALLY needed the identifier to be something constant (like the identifiers of objects in the standards library), I'm usually already deep in the code and I'm setting the identifiers within my code and not on a Grasshopper component.

**Comment by chriswmackey** [comment]
> This will break the workflows that will take a grid name as an input unless we update them every single time since it will changing randomly. 
If you really want to match it based on user-input, then use the `display_name` to do that.

**Comment by mostaphaRoudsari** [comment]
Thank you for the explanation. To make it easier for you. I understand why we need ID. I was part of that conversation and in fact I actually [initiated](https://3.basecamp.com/4298486/buckets/13923324/question_answers/2553952203) the whole conversation. You do not need to convince me about what I'm already convinced about. 😀 At the same time, I disagree with the details and reasoning here. It's not about the idea but the implementation.

I will get back to this later. This seems to be one of those decisions that is fixated in your mind. For now, I will add some workarounds to handle the additional random numbers at the end of the names.
